### ISSUE TITLE
could you provide a windows installation step-by-step guide?

### ISSUE THREAD

**Issue by Irismoon** [lfads/lfads-run-manager#20]
Hi, thanks for contributions.
I'm a newbie in both python and tensorflow. and try to use LFADS to process my local field potential data on a windows platform. But get confused by the installation guide on https://lfads.github.io/lfads-run-manager/. 
Specifically, several problem arise:
1.I already have python 3.7 installed . When I run the command: conda create --name tensorflow python=2.7 tensorflow-gpu. An error throwed: python 2.7 conflicts. So I install them separately as two environments. conda create --name py27 python==2.7 and conda create --name tensorflow tensorflow-gpu. Not sure if some problem will arise in this way.
2.About installing LFADS, the export path .... is for linux if I remember right. How exactly it work on windows?
Thanks .

Mango

**Comment by djoshea** [comment]
Hi Mango,

Unfortunately I haven't used Windows for any real development in quite a few years, and I don't have access to any Windows machines, so my ability to provide assistance for Windows is extremely limited. For (2), I've tried as much as possible within Matlab to use platform independent path related commands like `fullfile` so that the paths are constructed with the correct path separator on Windows. Ultimately, the files being generated should work on any platform, although you'd presumably need to use something like cygwin or the Windows Subsystem for Linux (WSL) to run these scripts directly. Otherwise you'd need to convert them to batch scripts yourself. If you come across specific errors with files being generated with incorrect path specifications, please file an issue. 

For (1), this is a more general question about Python virtual environments that isn't really specific to LFADS. I've mainly used Anaconda to manage environments on Mac and Linux and it is capable of supporting multiple versions of Python in different environments. Not sure what the issue you're having is, but it might be possible to find help on a more general forum like Stack Overflow? https://stackoverflow.com/questions/tagged/python

Sorry I can't be of more help! I'd recommend trying to run LFADS from linux if at all possible; it should make everything much easier.
Dan

**Comment by Irismoon** [comment]
Ok, guess I will try to find a Linux machine anyway:). Thanks for reply
