### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Guyuemaple** [lfads/lfads-run-manager#25]
Hi, thanks for sharing your work with us.

I met two problems when I used LFADS.

1. Followed the tutorial instruction, all the code is well with Matlab, but I encountered an error when running the 'run_lfadssqueue.py'. It always raised the OSError: [Errno 2] No such file or directory. All the path and file structure checked were not strange.

2. Can the LFADS run on Tensorflow (CPU) version? Or is the GPU  a must?

It is very kind of you if you can tell me some ways to solve problems.

Thanks!

**Comment by djoshea** [comment]
Hi Yue,

1. It's hard to debug without more info. Are you able to run the lfads_train.sh scripts directly? What happens if you run `nvidia-smi` at the command line? However, note that run_lfadsqueue.py is specifically designed to use the Nvidia GPUs available on your system, so if you don't have one, the queue cannot be used and you will need to run the training scripts directly.

2. I believe so, but it will be very slow. I haven't tested using it with the CPU version. 

Thanks and good luck!

**Comment by Guyuemaple** [comment]
It worked fine with lfads_train.sh file! And the only CPU is OK, but it took more than 12h. 😅

By the way, if I want to try VAE myself, how can I organize the spiketrian data better?

Thanks a lot!

**Comment by djoshea** [comment]
Great to hear you got it working, sounds it like it was the documented dependency of the lfadsqueue on `nvidia_smi` to track GPU usage and schedule the training runs.

Not sure what you mean by organizing the data better?

I'm going to close this since it sounds like the lfads-run-manager issue is resolved.
