### ISSUE TITLE
Reconstructed factors are distinct with real latent variables in lorenz example

### ISSUE THREAD

**Issue by NebulaWang** [lfads/lfads-run-manager#29]
Hi, I have run the lorenz_example successfully used same hyper-parameters as nature method papers, but i find that reconstructed factors are distinct with real ones(lorenz-system). I want to know the reason and to fix the model to reconstruct real system well. 
![Recons](https://user-images.githubusercontent.com/40286575/93007914-0c1d2d80-f5a1-11ea-938d-4725323424a9.jpg)

**Comment by djoshea** [comment]
Hi Xingyun, great to hear you've gotten the Lorenz example up and running. In cases like this where you have a synthetic ground truth, the factors inferred by LFADS may or may not match the factors in the data generating process. From your right hand plots, the reconstructed firing rates match the true firing rates fairly accurately, which is what LFADS is ultimately optimizing for. There may be a large space of nonlinear dynamical systems that can reproduce these dynamics on short timespans, and LFADS has identified one of them. (There's a bit of nuance here in that LFADS is a variational autoencoder, so its really optimizing for a distribution over firing rates which you are plotting the posterior mean of) It may be that in some cases you can recover the ground truth system more accurately, but in the neuroscience context where there is no ground truth to compare it to, the goal is to infer a set of latent factors that obey lawful dynamics while reproducing the observed neural dynamics we record.

As far as this specific example, any discrepancies with the chaotic RNN in the published paper may result from differences in the exact data generating process. The paper used the data generated by `run_generate_synth_data.sh` instead of the Matlab code provided here for convenience. https://github.com/lfads/models/tree/master/research/lfads

**Comment by NebulaWang** [comment]
Wonderful explanation! Thanks a lot! Your method really help me a lot to understand the latent dynamics relevant to bran function. Wish you and your team can achieve novel progresses in this area. Best wishes.
